name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  draftRelease:
    runs-on: ubuntu-latest

    name: Draft Release
    steps:
      - uses: actions/checkout@v4
      - name: Draft Release
        uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
